export const FIND_KONTRASEPSI_REQUEST = "FIND_KONTRASEPSI_REQUEST";
export const FIND_KONTRASEPSI_SUCCESS = "FIND_KONTRASEPSI_SUCCESS";
export const FIND_KONTRASEPSI_FAILURE = "FIND_KONTRASEPSI_FAILURE";

export const FIND_KONTRASEPSIS_REQUEST = "FIND_KONTRASEPSIS_REQUEST";
export const FIND_KONTRASEPSIS_SUCCESS = "FIND_KONTRASEPSIS_SUCCESS";
export const FIND_KONTRASEPSIS_FAILURE = "FIND_KONTRASEPSIS_FAILURE";

export const ADD_KONTRASEPSI_REQUEST = "ADD_KONTRASEPSI_REQUEST";
export const ADD_KONTRASEPSI_SUCCESS = "ADD_KONTRASEPSI_SUCCESS";
export const ADD_KONTRASEPSI_FAILURE = "ADD_KONTRASEPSI_FAILURE";

export const FIND_PROPINSI_REQUEST = "FIND_PROPINSI_REQUEST";
export const FIND_PROPINSI_SUCCESS = "FIND_PROPINSI_SUCCESS";
export const FIND_PROPINSI_FAILURE = "FIND_PROPINSI_FAILURE";

export const FIND_PROPINSIS_REQUEST = "FIND_PROPINSIS_REQUEST";
export const FIND_PROPINSIS_SUCCESS = "FIND_PROPINSIS_SUCCESS";
export const FIND_PROPINSIS_FAILURE = "FIND_PROPINSIS_FAILURE";

export const ADD_PROPINSI_REQUEST = "ADD_PROPINSI_REQUEST";
export const ADD_PROPINSI_SUCCESS = "ADD_PROPINSI_SUCCESS";
export const ADD_PROPINSI_FAILURE = "ADD_PROPINSI_FAILURE";

export const FIND_PEMAKAI_KONTRASEPSI_REQUEST =
  "FIND_PEMAKAI_KONTRASEPSI_REQUEST";
export const FIND_PEMAKAI_KONTRASEPSI_SUCCESS =
  "FIND_PEMAKAI_KONTRASEPSI_SUCCESS";
export const FIND_PEMAKAI_KONTRASEPSI_FAILURE =
  "FIND_PEMAKAI_KONTRASEPSI_FAILURE";

export const FIND_PEMAKAI_KONTRASEPSIS_REQUEST =
  "FIND_PEMAKAI_KONTRASEPSIS_REQUEST";
export const FIND_PEMAKAI_KONTRASEPSIS_SUCCESS =
  "FIND_PEMAKAI_KONTRASEPSIS_SUCCESS";
export const FIND_PEMAKAI_KONTRASEPSIS_FAILURE =
  "FIND_PEMAKAI_KONTRASEPSIS_FAILURE";

export const ADD_PEMAKAI_KONTRASEPSI_REQUEST =
  "ADD_PEMAKAI_KONTRASEPSI_REQUEST";
export const ADD_PEMAKAI_KONTRASEPSI_SUCCESS =
  "ADD_PEMAKAI_KONTRASEPSI_SUCCESS";
export const ADD_PEMAKAI_KONTRASEPSI_FAILURE =
  "ADD_PEMAKAI_KONTRASEPSI_FAILURE";
